#!/usr/bin/env python3
"""
SurgicalWorlds — Genie 3 for Surgery
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Optional, Tuple

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

import torch
import gradio as gr
from PIL import Image

from simulator.controls import get_control_scheme
from simulator.demo_engine import DemoSurgeryEngine
from simulator.engine import EngineConfig, SurgeryWorldEngine


# ── Global session ───────────────────────────────────────────────────────
_engine = None
_mode = "demo"  # "demo" | "model"
_scheme = None
_last_latency = 0.0


def _init_engine(
    surgery_type: str,
    use_model: bool,
    device: str,
    temperature: float,
) -> Tuple[str, Image.Image]:
    global _engine, _mode, _scheme, _last_latency
    _scheme = get_control_scheme(surgery_type)
    _last_latency = 0.0

    if use_model:
        try:
            cfg = EngineConfig(
                device=device,
                temperature=temperature,
                context_window=4,
                maskgit_steps=8,
            )
            _engine = SurgeryWorldEngine(cfg)
            _mode = "model"
            status = (
                "✅ **World model loaded** — frames are generated by the trained "
                "dynamics model (Genie 3-style autoregressive simulation)."
            )
        except FileNotFoundError as e:
            _engine = DemoSurgeryEngine(surgery_type=surgery_type)
            _mode = "demo"
            status = (
                f"⚠️ **Demo mode** — no trained checkpoints found.\n\n"
                f"Details: {e}"
            )
    else:
        _engine = DemoSurgeryEngine(surgery_type=surgery_type)
        _mode = "demo"
        status = "🎮 **Demo mode** — synthetic laparoscopic scene."

    frame = _engine.reset()
    return status, frame
