#!/usr/bin/env python3
"""
SurgicalWorlds — Genie 3 for Surgery

Playable laparoscopic surgery simulator. Users control instruments via
on-screen buttons (or keyboard) and the world model generates the next
surgical frame autoregressively.

Launch:
    python app/surgery_simulator.py
    python scripts/play_surgery.py
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Optional, Tuple

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

import torch
import gradio as gr
from PIL import Image

from simulator.controls import get_control_scheme
from simulator.demo_engine import DemoSurgeryEngine
from simulator.engine import EngineConfig, SurgeryWorldEngine


# ── Global session ──────────────────────────────────────────────────────────
_engine = None
_mode = "demo"  # "demo" | "model"
_scheme = None
_last_latency = 0.0


def _init_engine(
    surgery_type: str,
    use_model: bool,
    device: str,
    temperature: float,
) -> Tuple[str, Image.Image]:
    global _engine, _mode, _scheme, _last_latency
    _scheme = get_control_scheme(surgery_type)
    _last_latency = 0.0

    if use_model:
        try:
            cfg = EngineConfig(
                device=device,
                temperature=temperature,
                context_window=4,
                maskgit_steps=8,
            )
            _engine = SurgeryWorldEngine(cfg)
            _mode = "model"
            status = (
                "✅ **World model loaded** — frames are generated by the trained "
                "dynamics model (Genie 3-style autoregressive simulation)."
            )
        except FileNotFoundError as e:
            _engine = DemoSurgeryEngine(surgery_type=surgery_type)
            _mode = "demo"
            status = (
                f"⚠️ **Demo mode** — no trained checkpoints found.\n\n"
                f"Train with `python scripts/full_train.py --config configs/surgical_training.yaml` "
                f"then relaunch with **Use trained model** enabled.\n\n"
                f"Details: {e}"
            )
    else:
        _engine = DemoSurgeryEngine(surgery_type=surgery_type)
        _mode = "demo"
        status = (
            "🎮 **Demo mode** — synthetic laparoscopic scene with instrument physics. "
            "Enable **Use trained model** after training for real world-model generation."
        )

    frame = _engine.reset()
    return status, frame


def _do_step(action_id: int) -> Tuple[Image.Image, str, str]:
    global _last_latency
    if _engine is None:
        frame = Image.new("RGB", (512, 512), (20, 10, 10))
        return frame, "Press **New Procedure** to start.", ""

    result = _engine.step(action_id)
    _last_latency = result.latency_ms

    stats = (
        f"Step **{result.step_index}** · action `{action_id}` · "
        f"{result.latency_ms:.0f} ms · {result.session_frames} frames"
    )
    mode_label = "🧠 World Model" if _mode == "model" else "🎮 Demo"
    return result.frame, stats, mode_label


def _make_action_handler(action_id: int):
    def handler():
        img, stats, _ = _do_step(action_id)
        return img, stats
    return handler


def _export_session() -> Optional[str]:
    if _engine is None or not _engine.get_session_gif_frames():
        return None
    frames = _engine.get_session_gif_frames()
    path = os.path.join(ROOT, "inference_results", "surgery_session.gif")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    frames[0].save(
        path,
        save_all=True,
        append_images=frames[1:],
        duration=200,
        loop=0,
    )
    return path


def build_ui() -> gr.Blocks:
    scheme_lap = get_control_scheme("laparoscopic")
    scheme_robot = get_control_scheme("robotic")

    with gr.Blocks(
        title="SurgicalWorlds — Genie 3 for Surgery",
        theme=gr.themes.Soft(primary_hue="red", neutral_hue="slate"),
        css="""
        .viewport { border: 3px solid #8b1a1a; border-radius: 12px; }
        .control-btn { min-width: 100px !important; font-size: 1.05em !important; }
        .status-box { font-family: monospace; }
        """,
    ) as demo:
        gr.Markdown(
            """
            # 🏥 SurgicalWorlds
            ### Genie 3 for Surgery — Interactive Laparoscopic Simulation

            Control surgical instruments and watch the world model generate the next frame.
            Like [Genie 3](https://deepmind.google/discover/blog/genie-3-a-new-frontier-for-world-models/),
            but for laparoscopic procedures — no action labels required during training.
            """
        )

        with gr.Row():
            with gr.Column(scale=3):
                viewport = gr.Image(
                    label="Laparoscopic Viewport",
                    type="pil",
                    height=520,
                    elem_classes=["viewport"],
                    show_label=True,
                )
                stats = gr.Markdown("Press **New Procedure** to begin your simulation.", elem_classes=["status-box"])

            with gr.Column(scale=2):
                status_box = gr.Markdown("")

                surgery_type = gr.Radio(
                    choices=["laparoscopic", "robotic"],
                    value="laparoscopic",
                    label="Surgery type",
                )
                use_model = gr.Checkbox(
                    label="Use trained world model (requires checkpoints)",
                    value=False,
                )
                device = gr.Radio(
                    choices=["cuda", "cpu", "mps"],
                    value="cuda" if torch.cuda.is_available() else ("mps" if torch.backends.mps.is_available() else "cpu"),
                    label="Device",
                )
                temperature = gr.Slider(0.0, 1.5, value=0.4, step=0.1, label="Sampling temperature")

                gr.Markdown("### Instrument Controls")
                gr.Markdown(
                    "*Each button press = one Genie 3 action token → next predicted frame*"
                )

                control_buttons = []
                btn_row_refs = []

                def _rebuild_controls(stype):
                    s = get_control_scheme(stype)
                    return s.help_text()

                controls_help = gr.Markdown(scheme_lap.help_text())

                with gr.Group():
                    gr.Markdown("**Primary instrument**")
                    with gr.Row():
                        btn_idle = gr.Button("⏸ Hold", elem_classes=["control-btn"])
                        btn_grasp = gr.Button("✊ Grasp", elem_classes=["control-btn"])
                        btn_release = gr.Button("🖐 Release", elem_classes=["control-btn"])
                    with gr.Row():
                        btn_left = gr.Button("← Left", elem_classes=["control-btn"])
                        btn_up = gr.Button("↑ Up", elem_classes=["control-btn"])
                        btn_down = gr.Button("↓ Down", elem_classes=["control-btn"])
                        btn_right = gr.Button("→ Right", elem_classes=["control-btn"])
                    with gr.Row():
                        btn_camera = gr.Button("📷 Camera Pan", elem_classes=["control-btn"])

                with gr.Row():
                    new_proc = gr.Button("🔄 New Procedure", variant="primary", size="lg")
                    export_btn = gr.Button("💾 Export Session GIF", size="lg")

                export_file = gr.File(label="Session recording", visible=True)

        lap_actions = scheme_lap.actions
        rob_actions = scheme_robot.actions

        def step_lap(action_name):
            s = get_control_scheme("laparoscopic")
            return _do_step(s.action_id(action_name))[:2]

        def step_rob(action_name):
            s = get_control_scheme("robotic")
            return _do_step(s.action_id(action_name))[:2]

        def on_new_proc(stype, model, dev, temp):
            return _init_engine(stype, model, dev, temp)

        new_proc.click(
            on_new_proc,
            inputs=[surgery_type, use_model, device, temperature],
            outputs=[status_box, viewport],
        ).then(lambda: "Simulation started. Use instrument controls.", outputs=[stats])

        btn_idle.click(lambda: step_lap("idle"), outputs=[viewport, stats])
        btn_grasp.click(lambda: step_lap("grasp"), outputs=[viewport, stats])
        btn_release.click(lambda: step_lap("release"), outputs=[viewport, stats])
        btn_left.click(lambda: step_lap("left"), outputs=[viewport, stats])
        btn_right.click(lambda: step_lap("right"), outputs=[viewport, stats])
        btn_up.click(lambda: step_lap("up"), outputs=[viewport, stats])
        btn_down.click(lambda: step_lap("down"), outputs=[viewport, stats])
        btn_camera.click(lambda: step_lap("camera"), outputs=[viewport, stats])

        surgery_type.change(
            lambda st: get_control_scheme(st).help_text(),
            inputs=[surgery_type],
            outputs=[controls_help],
        )

        export_btn.click(_export_session, outputs=[export_file])

        demo.load(
            on_new_proc,
            inputs=[surgery_type, use_model, device, temperature],
            outputs=[status_box, viewport],
        )

        gr.Markdown(
            """
            ---
            **How it works (Genie 3 architecture):**
            1. **Video tokenizer** compresses surgical frames → discrete tokens
            2. **Action tokenizer** learns latent instrument motions from video (no labels)
            3. **Dynamics model** predicts the next frame given your action input

            Train on your own videos: `python scripts/prepare_surgical_data.py --input /path/to/videos/`
            """
        )

    return demo


def main():
    parser = argparse.ArgumentParser(description="SurgicalWorlds — Genie 3 for Surgery")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=7860)
    parser.add_argument("--share", action="store_true", help="Create public Gradio link")
    args = parser.parse_args()

    os.chdir(ROOT)
    demo = build_ui()
    demo.launch(server_name=args.host, server_port=args.port, share=args.share)


if __name__ == "__main__":
    main()
