# Stage 2 — latent actions
batch_size_per_gpu: 4
gradient_accumulation_steps: 24
n_updates: 8000
learning_rate: 0.0001
log_interval: 1000

embed_dim: 64
num_heads: 8
hidden_dim: 256
num_blocks: 4

checkpoint: null
