batch_size_per_gpu: 8
gradient_accumulation_steps: 8
n_updates: 12000
learning_rate: 0.005
log_interval: 500
use_actions: true
embed_dim: 48
num_heads: 8
hidden_dim: 192
num_blocks: 8
video_tokenizer_path:
latent_actions_path:
checkpoint:
